################ English language ##################
[en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 1

[es]
languageName = "Es"
languageCode = "es-PE"
contentDir = "content/spanish"
weight = 2